/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Form;

import Controller.Service;
import Database.MyConnect;
import java.io.File;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;



/**
 *
 * @author tuann
 */
public class Baocaothongke_panel extends javax.swing.JPanel {

    /**
     * Creates new form Baocaothongke_panel
     */
    private MyConnect mc = new MyConnect();
    private Service sv = new Service();
    private File file = new File("Thống kê doanh thu.xls");

    public Baocaothongke_panel() {
        initComponents();

        sv.Loadata(tableThongke, "donhang");
        Cost();
        int Tongsodon = tableThongke.getRowCount();
        txtTongdon.setText("Tổng số đơn bán ra "+String.valueOf(Tongsodon));
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableThongke = new javax.swing.JTable();
        txtTongoanhthu = new javax.swing.JTextField();
        btlXuatfile = new javax.swing.JButton();
        txtTongdon = new javax.swing.JTextField();

        jTextField1.setBackground(new java.awt.Color(51, 204, 255));
        jTextField1.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jTextField1.setForeground(new java.awt.Color(0, 0, 204));
        jTextField1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField1.setText("Thống Kê Doanh Thu");

        tableThongke.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Mã đơn", "Mã khách hàng", "Số điện thoại", "Địa chỉ", "Tên sản phẩm", "Giá bán", "Số lượng", "Ngày bán"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Double.class, java.lang.Integer.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tableThongke);

        txtTongoanhthu.setEnabled(false);

        btlXuatfile.setText("Xuất hóa đơn");
        btlXuatfile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btlXuatfileActionPerformed(evt);
            }
        });

        txtTongdon.setEnabled(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, 631, Short.MAX_VALUE)
                    .addComponent(jScrollPane1))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtTongoanhthu, javax.swing.GroupLayout.DEFAULT_SIZE, 283, Short.MAX_VALUE)
                    .addComponent(txtTongdon))
                .addGap(52, 52, 52)
                .addComponent(btlXuatfile)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtTongoanhthu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(21, 21, 21))
                    .addComponent(btlXuatfile, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addComponent(txtTongdon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(32, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btlXuatfileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btlXuatfileActionPerformed
        // TODO add your handling code here:
       sv.Export2Excel(tableThongke, file);
    }//GEN-LAST:event_btlXuatfileActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btlXuatfile;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTable tableThongke;
    private javax.swing.JTextField txtTongdon;
    private javax.swing.JTextField txtTongoanhthu;
    // End of variables declaration//GEN-END:variables

    
    private void Cost() {
        Connection conn = new MyConnect().getConnection();
        PreparedStatement statement = null;
        ResultSet resultSet = null;

        try {
            String sql = " SELECT SUM(giaBan) FROM donhang ";
            statement = conn.prepareStatement(sql);
            resultSet = statement.executeQuery();

            if (resultSet.next()) {
                int sum = resultSet.getInt(1);
                txtTongoanhthu.setText("Tổng doanh thu "+String.valueOf(sum));
            }

        } catch (Exception e) {
            e.printStackTrace();
        }
    }
    
    

}
